### PR TITLE
Get data sources only when they are needed

### PR DESCRIPTION
**Pull request by hcarneiro**
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3971

With this change we've changed the request of data sources to the vue component that actually needs it.
This reduces the time it takes to show the initial interface, but might increase the time it takes to load the "Add markers" UI.

### CODE REVIEW

**Comment by ibroom** [comment]
@squallstar as you did the PR I am checking that you understand and believe Hugo has implemented the change is the most efficient way and that you do not have any concerns?

**Comment by squallstar** [comment]
@ibroom yes, I approve the change because I reviewed it and it's in line with my expectations for the data flow for this component.

**Comment by ibroom** [comment]
Is it the most optimum @squallstar based on the fact the support ticket reports 850kb returned when getting a list of data sources?

**Comment by squallstar** [comment]
@ibroom I've already replied in regards to this topic here https://github.com/Fliplet/fliplet-studio/issues/3971#issuecomment-486982265

**Pull request merged**
